baseURL = "https://anatofuz.net"
theme = "aafu"
languageCode = "ja"

[params]
  title = "AnaTofuZ's page"
  author = "AnaTofuZ"
  description = "Takahiro SHIMIZU"
  blog = "anatofuz.hatenablog.com"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false


    # Profile section
    [params.profile]
      name = "Takahiro Shimizu"
        tagline = "@AnaTofuZ"
        location = "沖縄とか"
      photo = "icon.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/AnaTofuZ"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/AnaTofuZ"
            title = "Twitter"
        [[params.social.list]]
            class = "fab"
            icon = "fa-facebook"
            url = "https://www.facebook.com/AnaTofuZ/"
            title = "FaceBook"
 

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "education"
#    [[params.showInAccordion]]
#        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"
    [[params.showInAccordion]]
        item = "link"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "沖縄にいる大学院生。インターネットではアナグラ(`AnaTofuZ`)と呼ばれています。低レイヤー周りを研究していますが、 関係ないプログラミングをしている時間の方が長いかもしれません。プログラミング言語ではPerlが好きですが、最近はgolangとContianuton Based Cを書いています。"

#    [params.experience]
#        title = "Experiences"
#        icon = "fas fa-briefcase"
#
#        [[params.experience.list]]
#            position = "大学院生"
#            dates = "2018 - 2019"
#            link = "#"
#            company = "Company Name"
#


    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "修士(在籍中)"
            college = "琉球大学大学院理工学研究科情報工学専攻"
            dates = "2019 - "
        [[params.education.list]]
            degree = "学部"
            college = "琉球大学工学部情報工学科"
            dates = "2015 - 2019"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Acme::MadokaMagica"
            url = "https://github.com/AnaTofuZ/perl-acme-MadokaMagica"
            description = "初めて作ったPerlモジュール。魔法少女まどか☆マギカの登場人物の情報が取得できます。"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Perl"
            skillrating = 70
 
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
        hobby = "プログラミング"
        [[params.hobby.list]]
        hobby = "Perl考古学(Perl1.0, Perl2.0)"
        [[params.hobby.list]]
        hobby = "Raku"
        [[params.hobby.list]]
        hobby = "落語"
        [[params.hobby.list]]
        hobby = "dlsiteで同人ゲーを買うこと"

    [params.link]
        title = "Links"
        icon = "fas fa-briefcase"

        [[params.link.list]]
            title  = "SpeakerDeck"
            link = "https://speakerdeck.com/AnaTofuZ"
            details = "登壇資料を置いています"
 
        [[params.link.list]]
            title  = "並列信頼研"
            link = "http://www.cr.ie.u-ryukyu.ac.jp/"
            details = "在籍している研究室です"

        [[params.link.list]]
            title  = "crgrowi"
            link = "https://growi.cr.ie.u-ryukyu.ac.jp/"
            details = "研究室のgrowiです"
